apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skadoosh-pvc
  namespace: kuzka

spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 1Gi
