image:
  tag: v4.0.2

storageClass:
  name: nfs-crimson
  defaultClass: true
  onDelete: delete

nfs:
  server: 207.246.100.141
  path: /mnt/blockstorage/skidobo
  volumeName: nfs-crimson
  reclaimPolicy: Delete

resources:
  requests:
    cpu: "0.5"
    memory: 128Mi
  limits:
    cpu: 1
    memory: 1024Mi
