domain: rkth.io

ingress:
  enabled: true
  certManager: true
  subdomain: auth

  tls:
    enabled: true
    secret: authelia-tls

  traefikCRD:
    enabled: true
    entryPoints:
      - websecure
    sticky: true

pod:
  kind: StatefulSet
  replicas: 1

  env:
    - name: TZ
      value: "USA/Los_Angeles"

  resources:
    requests:
      cpu: "0.25"
      memory: 128Mi
    limits:
      cpu: "2.00"
      memory: 1Gi

configMap:
  enabled: true

  log:
    level: debug

  webauthn:
    display_name: rkth.io

  authentication_backend:
    password_reset:
      disable: false
    ldap:
      enabled: true
      implementation: custom
      url: ldap://lldap-service.appspace.svc.cluster.local:3890
      base_dn: dc=rkth,dc=io
      username_attribute: uid
      additional_users_dn: ou=people
      additional_groups_dn: ou=groups
      users_filter: "(&({username_attribute}={input})(objectClass=person))"
      groups_filter: "(member={dn})"
      group_name_attribute: cn
      mail_attribute: mail
      display_name_attribute: displayName
      user: uid=admin,ou=people,dc=rkth,dc=io
      password: 3F3frLFonmT43DndDGU_Z!WPmge8K4
    file:
      enabled: false


  access_control:
    default_policy: deny
    rules:
    - domain: '*.rkth.io'
      policy: one_factor
      methods:
        - GET
        - POST
        - PUT

  session:
    name: rktho
    expiration: 12h
    inactivity: 30m
    remember_me_duration: 15d

    redis:
      enabled: true
      enabledSecret: true
      maximum_active_connections: 8
      minimum_idle_connections: 1
      host: redis.databases.svc.cluster.local
      port: 26379

      high_availability:
        enabled: true
        enabledSecret: true
        sentinel_name: redis-master

  storage:
    local:
      enabled: false
    mysql:
      enabled: false
      host: mariadb.databases.svc.cluster.local
      port: 3306
      database: authelia
      username: authelia
      timeout: 5s
      tls:
        enabled: false
    postgres:
      enabled: true
      host: postgresql-ha-postgresql.databases.svc.cluster.local
      database: authelia
      username: authelia


  regulation:
    max_retries: 3
    find_time: 2m
    ban_time: 30m

  notifier:
    disable_startup_check: false
    smtp:
      enabled: true
      enabledSecret: true
      host: smtp.gmail.com
      port: 587
      username: rcnoetic@gmail.com
      sender: authelia@rkth.io
      subject: "AUTHELIA {title}"

  identity_providers:
    oidc:
      enabled: false


certificates:
  existingSecret: "authelia-tls"

secret:
  existingSecret: authelia-secret
  jwt:
    key: jwt
  ldap:
    key: ldap-password
  storage:
    key: storage-password
  storageEncryptionKey:
    key: storageEncryptionKey
  session:
    key: session
  redis:
    key: REDIS_PASSWORD
  redisSentinel:
    key: redis-sentinel
  smtp:
    key: smtp
  oidcPrivateKey:
    key: oidcPrivateKey
  oidcHMACSecret:
    key: oidcHMACSecret
