apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: miniflux-tls
  namespace: appspace
spec:
  secretName: miniflux-tls
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - 'flux.rkth.io'
