apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: miniflux-secret
  namespace: appspace
spec:
  itemPath: "vaults/kube/items/miniflux"

---

apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: miniflux-db-secret
  namespace: appspace
spec:
  itemPath: "vaults/kube/items/miniflux-db"
