env:
  BASE_URL: https://flux.rkth.io
  DATABASE_URL:
    secretKeyRef:
      name: miniflux-secret
      key: dbUrl

ingress:
  main:
    enabled: true
    hosts:
      - host: flux.rkth.io
        paths:
          - path: /
            pathType: Prefix

postgresql:
  enabled: true
