env:
  BASE_URL:
    secretKeyRef:
      name: miniflux-secret
      key: baseUrl
  DATABASE_URL:
    secretKeyRef:
      name: miniflux-secret
      key: dbUrl

ingress:
  main:
    enabled: true
    hosts:
      - host: flux.rkth.io
        paths:
          - path: /
            pathType: Prefix
