apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-dep
  namespace: appspace
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      volumes:
        - name: homepage-config
          persistentVolumeClaim:
            claimName: homepage-pvc
      containers:
      - name: homepage
        image: ghcr.io/benphelps/homepage:latest
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: homepage-config
            mountPath: "/app/config"

---

apiVersion: v1
kind: Service
metadata:
  name: homepage-svc
  namespace: appspace
spec:
  selector:
    app: homepage
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-ing
  namespace: appspace
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`rkth.io`)
      services:
        - kind: Service
          name: homepage-svc
          port: 3000

  tls:
    secretName: homepage-cert

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-pvc
  namespace: appspace
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Mi

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-cert
  namespace: appspace
spec:
  secretName: homepage-cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
  - 'rkth.io'
