apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-cert
  namespace: kuzka
spec:
  secretName: homepage-cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
  - 'rkth.io'
