global:
  storageClass: nfs-crimson

  postgresql:
    auth:
      username: authelia
      database: authelia
      existingSecret: postgre-secret

      secretKeys:
        adminPasswordKey: admin-password
        userPasswordKey: user-password
        replicationPasswordKey: replication-password


primary:
  initdb:
    user: authelia
  persistence:
    size: 1Gi
