apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkding-tls
  namespace: appspace

spec:
  secretName: linkding-tls
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - 'lnk.rkth.io'
