env:
  - name: TZ
    value: "USA/Los_Angeles"
  - name: LD_ENABLE_AUTH_PROXY
    value: "true"
  - name: LD_AUTH_PROXY_USERNAME_HEADER
    value: "HTTP_REMOTE_USER"
  - name: LD_AUTH_PROXY_LOGOUT_URL
    value: "https://auth.rkth.io/logout"

image:
  tag: 1.21.0

ingressRoute:
  create: true
  entryPoints:
    - websecure

  rule: "Host(`lnk.rkth.io`)"
  tlsSecretName: linkding-tls

persistentVolumeClaim:
  create: true
  storageClassName: longhorn
  size: 1Gi
