apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-tls-cert
  namespace: argocd

spec:
  secretName: argo-cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
  - 'acd.rkth.io'
