apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acd-tls-cert
  namespace: argocd

spec:
  secretName: argocd-server-tls
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
  - 'acd.rkth.io'
