global:
  storageClass: nfs-crimson

  postgresql:
    auth:
      username: authelia
      database: authelia
      existingSecret: postgres-secret

      secretKeys:
        adminPasswordKey: admin-password
        userPasswordKey: user-password
        replicationPasswordKey: replication-password

auth:
  username: authelia
  database: authelia
  existingSecret: postgres-secret

  secretKeys:
    adminPasswordKey: admin-password
    userPasswordKey: user-password
    replicationPasswordKey: replication-password

primary:
  persistence:
    size: 1Gi
