global:
  storageClass: nfs-crimson

  postgresql:
    auth:
      postgresPassword: authelia
      username: authelia
      password: authelia
      database: authelia
      # existingSecret: postgres-secret

      # secretKeys:
      #   adminPasswordKey: admin-password
      #   userPasswordKey: user-password
      #   replicationPasswordKey: replication-password

auth:
  postgresPassword: authelia
  username: authelia
  password: authelia
  database: authelia
  replicationPassword: authelia
  # existingSecret: postgres-secret

  # secretKeys:
  #   adminPasswordKey: admin-password
  #   userPasswordKey: user-password
  #   replicationPasswordKey: replication-password

primary:
  persistence:
    size: 1Gi
