apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
  namespace: cert-manager

spec:
  acme:
    email: rcnoetic@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        cloudflare:
          email: rcnoetic@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api
            key: credential
