global:
  storageClass: nfs-crimson

auth:
  existingSecret: redis-secret
  existingSecretPasswordKey: password

master:
  persistence:
    size: 1Gi

replica:
  replicaCount: 3
  persistence:
    size: 1Gi

sentinel:
  enabled: true
  masterSet: redis-master

  image:
    debug: true
