global:
  storageClass: nfs-crimson

# architecture: standalone

auth:
  existingSecret: redis-secret
  existingSecretPasswordKey: password

master:
  # kind: Deployment
  persistence:
    size: 1Gi

replica:
  persistence:
    size: 1Gi

sentinel:
  enabled: true
  masterSet: redis-master

  # image:
  #   debug: true
