apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  project: default

  source:
    repoURL: https://github.com/rishikanthc/kdev.git
    targetRevision: HEAD
    path: argocd-ingress

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true
