apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-provider
  namespace: argocd


spec:
  project: default

  source:
    repoURL: https://github.com/rishikanthc/kdev.git
    targetRevision: HEAD
    path: cert-provider

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true
