apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-provider
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  project: default

  source:
    repoURL: https://github.com/rishikanthc/kdev.git
    targetRevision: HEAD
    path: cert-manager
    plugin:
      name: argocd-vault-plugin

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true
