apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lldap
  namespace: argocd
  finalizers:
      # The default behaviour is foreground cascading deletion
      - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/rishikanthc/kdev.git
    targetRevision: HEAD
    path: lldap

  destination:
    server: https://kubernetes.default.svc
    namespace: appspace

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true
