apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux
  namespace: argocd
  finalizers:
      # The default behaviour is foreground cascading deletion
      - resources-finalizer.argocd.argoproj.io

spec:
  project: homelab

  sources:
    - repoURL: https://github.com/rishikanthc/helm-charts.git
      targetRevision: HEAD
      path: miniflux
      helm:
        releaseName: miniflux
        # valueFiles:
        #   - $values/miniflux/values.yaml

    # - repoURL: https://github.com/rishikanthc/kdev.git
    #   targetRevision: HEAD
    #   path: miniflux
    #   ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: appspace

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true
