apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: cluster-tools
  finalizers:
      # The default behaviour is foreground cascading deletion
      - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: nfs-subdir-external-provisioner
      helm:
        valueFiles:
        - $values/nfs-provisioner/values.yaml

    - repoURL: https://github.com/rishikanthc/kdev.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-tools

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true
