apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-ha
  namespace: argocd
  finalizers:
      # The default behaviour is foreground cascading deletion
      - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql-hl
      targetRevision: 11.9.0
      helm:
        valueFiles:
          - $values/postgresql-ha/values.yaml

    - repoURL: https://github.com/rishikanthc/kdev.git
      targetRevision: HEAD
      path: postgresql-ha
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: databases

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true
