apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volume-configs
  namespace: argocd
  finalizers:
      # The default behaviour is foreground cascading deletion
      - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rishikanthc/kdev.git
    targetRevision: HEAD
    path: volumes
  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
