apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
      # The default behaviour is foreground cascading deletion
      - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis-cluster
      targetRevision: 8.8.2
      helm:
        valueFiles:
          - $values/redis/values.yaml

    - repoURL: https://github.com/rishikanthc/kdev.git
      targetRevision: HEAD
      ref: values

    - repoURL: https://github.com/rishikanthc/kdev.git
      targetRevision: HEAD
      path: redis/secret.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: databases

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true
