apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-config
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/rishikanthc/kdev.git
    targetRevision: HEAD
    path: traefik

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
